# Import Libraries and Datasets

In [1]:
# Import Libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Import prepared population data set; includes population estimates by state from 2010 - 2022
pop = pd.read_csv(r"C:\Users\miche\DA_Obesity and COVID19\02 Data\Prepared Data\04.03 CENSUS 2010_2022.csv")

In [3]:
# Import prepared COVID Deaths by state from 2020 - 2022
covid = pd.read_csv(r"C:\Users\miche\DA_Obesity and COVID19\02 Data\Prepared Data\03.02 COVID Deaths_final.csv")

# Review Data
### population

In [4]:
pop.head()

,State,2010 Population,2011 Population,2012 Population,2013 Population,2014 Population,2015 Population,2016 Population,2017 Population,2018 Population,2019 Population,2020 Population,2021 Population,2022 Population
0,Alabama,4779736,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185,5024279,5039877,5061555
1,Alaska,710231,722128,730443,737068,736283,737498,741456,739700,735139,731545,733391,732673,734543
2,Arizona,6392017,6472643,6554978,6632764,6730413,6829676,6941072,7044008,7158024,7278717,7151502,7276316,7350007
3,Arkansas,2915918,2940667,2952164,2959400,2967392,2978048,2989918,3001345,3009733,3017804,3011524,3025891,3035055
4,California,37253956,37638369,37948800,38260787,38596972,38918045,39167117,39358497,39461588,39512223,39538223,39237836,39403159

In [5]:
pop.columns

Index(['State', '2010 Population', '2011 Population', '2012 Population ',
       '2013 Population', '2014 Population', '2015 Population',
       '2016 Population', '2017 Population', '2018 Population',
       '2019 Population', '2020 Population', '2021 Population',
       '2022 Population'],
      dtype='object')

In [6]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             51 non-null     object
 1   2010 Population   51 non-null     int64
 2   2011 Population   51 non-null     int64
 3   2012 Population   51 non-null     int64
 4   2013 Population   51 non-null     int64
 5   2014 Population   51 non-null     int64
 6   2015 Population   51 non-null     int64
 7   2016 Population   51 non-null     int64
 8   2017 Population   51 non-null     int64
 9   2018 Population   51 non-null     int64
 10  2019 Population   51 non-null     int64
 11  2020 Population   51 non-null     int64
 12  2021 Population   51 non-null     int64
 13  2022 Population   51 non-null     int64
dtypes: int64(13), object(1)
memory usage: 5.7+ KB

In [7]:
pop.describe()

,2010 Population,2011 Population,2012 Population,2013 Population,2014 Population,2015 Population,2016 Population,2017 Population,2018 Population,2019 Population,2020 Population,2021 Population,2022 Population
count,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01
mean,6.053834e+06,6.108958e+06,6.153549e+06,6.195955e+06,6.241196e+06,6.286964e+06,6.332183e+06,6.372265e+06,6.405637e+06,6.436069e+06,6.499006e+06,6.507720e+06,6.545544e+06
std,6.823984e+06,6.901810e+06,6.967073e+06,7.029241e+06,7.100271e+06,7.172361e+06,7.235904e+06,7.288670e+06,7.327258e+06,7.360660e+06,7.408023e+06,7.397955e+06,7.447394e+06
min,5.636260e+05,5.672990e+05,5.763050e+05,5.821220e+05,5.825310e+05,5.856130e+05,5.842150e+05,5.789310e+05,5.776010e+05,5.787590e+05,5.768510e+05,5.788030e+05,5.800670e+05
25%,1.696962e+06,1.712291e+06,1.724314e+06,1.732560e+06,1.740300e+06,1.746554e+06,1.756702e+06,1.767360e+06,1.777414e+06,1.789606e+06,1.816411e+06,1.841941e+06,1.852912e+06
50%,4.339367e+06,4.369821e+06,4.386346e+06,4.404659e+06,4.414349e+06,4.425976e+06,4.438182e+06,4.452268e+06,4.461153e+06,4.467673e+06,4.505836e+06,4.509394e+06,4.523562e+06
75%,6.636084e+06,6.720105e+06,6.780032e+06,6.838650e+06,6.908626e+06,6.996666e+06,7.117922e+06,7.233685e+06,7.340946e+06,7.446805e+06,7.428392e+06,7.507504e+06,7.586606e+06
max,3.725396e+07,3.763837e+07,3.794880e+07,3.826079e+07,3.859697e+07,3.891804e+07,3.916712e+07,3.935850e+07,3.946159e+07,3.951222e+07,3.953822e+07,3.923784e+07,3.940316e+07

In [8]:
pop.shape

(51, 14)

### COVID deaths

In [9]:
covid.head()

,State,2020 COVID-19 Deaths,2020 COVID-Like Deaths,2021 COVID-19 Deaths,2021 COVID-Like Deaths,2022 COVID-19 Deaths,2022 COVID-Like Deaths
0,Alabama,6706,9870,9719,12496,3947,6134
1,Alaska,254,434,839,1005,311,478
2,Arizona,9321,13237,14060,17518,5172,7994
3,Arkansas,4027,6215,5336,7264,2558,4188
4,California,33578,52630,48327,64106,19836,33271

In [10]:
covid.columns

Index(['State', '2020 COVID-19 Deaths', '2020 COVID-Like Deaths',
       '2021 COVID-19 Deaths', '2021 COVID-Like Deaths',
       '2022 COVID-19 Deaths', '2022 COVID-Like Deaths'],
      dtype='object')

In [12]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   51 non-null     object
 1   2020 COVID-19 Deaths    51 non-null     int64
 2   2020 COVID-Like Deaths  51 non-null     int64
 3   2021 COVID-19 Deaths    51 non-null     int64
 4   2021 COVID-Like Deaths  51 non-null     int64
 5   2022 COVID-19 Deaths    51 non-null     int64
 6   2022 COVID-Like Deaths  51 non-null     int64
dtypes: int64(6), object(1)
memory usage: 2.9+ KB

In [13]:
covid.describe()

,2020 COVID-19 Deaths,2020 COVID-Like Deaths,2021 COVID-19 Deaths,2021 COVID-Like Deaths,2022 COVID-19 Deaths,2022 COVID-Like Deaths
count,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000
mean,7125.156863,10553.274510,8904.647059,11837.450980,4279.058824,6792.901961
std,7578.975573,11160.936414,10659.253307,13783.601074,4324.949435,6970.532988
min,145.000000,428.000000,308.000000,568.000000,311.000000,478.000000
25%,1634.500000,2575.000000,2305.000000,3139.000000,1043.000000,1803.500000
50%,5162.000000,7977.000000,5907.000000,8118.000000,2998.000000,4920.000000
75%,9055.000000,13804.000000,9886.500000,13342.000000,5507.000000,8316.500000
max,33578.000000,52630.000000,48786.000000,64106.000000,19836.000000,33271.000000

In [14]:
covid.shape

(51, 7)

# Merge COVID-19 Death and Population datasets
#### Using a full outer join

In [15]:
# Test merge without overwriting
pd.merge(covid,pop, on = ['State'], indicator = True)

,State,2020 COVID-19 Deaths,2020 COVID-Like Deaths,2021 COVID-19 Deaths,2021 COVID-Like Deaths,2022 COVID-19 Deaths,2022 COVID-Like Deaths,2010 Population,2011 Population,2012 Population,...,2014 Population,2015 Population,2016 Population,2017 Population,2018 Population,2019 Population,2020 Population,2021 Population,2022 Population,_merge
0,Alabama,6706,9870,9719,12496,3947,6134,4779736,4799069,4815588,...,4841799,4852347,4863525,4874486,4887681,4903185,5024279,5039877,5061555,both
1,Alaska,254,434,839,1005,311,478,710231,722128,730443,...,736283,737498,741456,739700,735139,731545,733391,732673,734543,both
2,Arizona,9321,13237,14060,17518,5172,7994,6392017,6472643,6554978,...,6730413,6829676,6941072,7044008,7158024,7278717,7151502,7276316,7350007,both
3,Arkansas,4027,6215,5336,7264,2558,4188,2915918,2940667,2952164,...,2967392,2978048,2989918,3001345,3009733,3017804,3011524,3025891,3035055,both
4,California,33578,52630,48327,64106,19836,33271,37253956,37638369,37948800,...,38596972,38918045,39167117,39358497,39461588,39512223,39538223,39237836,39403159,both
5,Colorado,5073,7297,6207,7983,2998,4792,5029196,5121108,5192647,...,5350101,5450623,5539215,5611885,5691287,5758736,5773714,5812069,5877308,both
6,Connecticut,6298,7977,3153,4582,2268,3848,3574097,3588283,3594547,...,3594524,3587122,3578141,3573297,3571520,3565287,3605944,3605597,3608222,both
7,Delaware,1096,1577,1266,1695,798,1233,897934,907381,915179,...,932487,941252,948921,956823,965479,973764,989948,1003384,1012171,both
8,District of Columbia,1004,1429,707,1058,397,673,601723,619800,634924,...,662328,675400,685815,694906,701547,705749,689545,670050,675743,both
9,Florida,21827,35229,38874,51305,15793,26555,18801310,19053237,19297822,...,19845911,20209042,20613477,20963613,21244317,21477737,21538187,21781128,22029446,both
10,Georgia,10454,15137,17309,21442,6691,10136,9687653,9802431,9901430,...,10067278,10178447,10301890,10410330,10511131,10617423,10711908,10799566,10892225,both
11,Hawaii,365,1045,744,1398,576,1186,1360301,1379329,1394804,...,1414538,1422052,1427559,1424393,1420593,1415872,1455271,1441553,1448324,both
12,Idaho,1541,2161,2785,3337,998,1486,1567582,1583910,1595324,...,1631112,1651059,1682380,1717715,1750536,1787065,1839106,1900923,1928701,both
13,Illinois,16721,23335,11787,16959,8032,12488,12830632,12867454,12882510,...,12884493,12858913,12820527,12778828,12723071,12671821,12812508,12671469,12658205,both
14,Indiana,9775,14280,10054,13572,5458,8554,6483802,6516528,6537703,...,6593644,6608422,6634304,6658078,6695497,6732219,6785528,6805985,6832833,both
15,Iowa,4769,6633,3526,5045,1992,3291,3046355,3066336,3076190,...,3109350,3120960,3131371,3141550,3148618,3155070,3190369,3193079,3205306,both
16,Kansas,3510,5071,3806,5125,2180,3314,2853118,2869225,2885257,...,2900475,2909011,2910844,2908718,2911359,2913314,2937880,2934582,2941370,both
17,Kentucky,4619,8524,8694,12154,5166,8079,4339367,4369821,4386346,...,4414349,4425976,4438182,4452268,4461153,4467673,4505836,4509394,4523562,both
18,Louisiana,7066,9352,6918,8832,2869,4218,4533372,4575625,4600972,...,4644013,4664628,4678135,4670560,4659690,4648794,4657757,4624047,4631603,both
19,Maine,465,1417,1433,2288,960,1764,1328361,1328284,1327729,...,1330513,1328262,1331317,1334612,1339057,1344212,1362359,1372247,1375904,both
20,Maryland,6729,10136,6101,9008,3921,6434,5773552,5839419,5886992,...,5957283,5985562,6003323,6023868,6035802,6045680,6177224,6165129,6197760,both
21,Massachusetts,10221,14227,5578,8534,3882,6515,6547629,6613583,6663005,...,6762596,6794228,6823608,6859789,6882635,6892503,7029917,6984723,7021147,both
22,Michigan,12342,18113,14945,19693,7310,11327,9883640,9882412,9897145,...,9929848,9931715,9950571,9973114,9984072,9986857,10077331,10050811,10064741,both
23,Minnesota,5834,8574,5181,7413,2980,5013,5303925,5346143,5376643,...,5451079,5482032,5522744,5566230,5606249,5639632,5706494,5707390,5741012,both
24,Mississippi,5162,7599,5907,8118,3007,4920,2967297,2978731,2983816,...,2990468,2988471,2987938,2988510,2981020,2976149,2961279,2949965,2948520,both
25,Missouri,8059,11656,8946,12036,4930,7652,5988927,6010275,6024367,...,6056202,6071732,6087135,6106670,6121623,6137428,6154913,6168187,6183125,both
26,Montana,1269,1782,1816,2294,673,1098,989415,997316,1003783,...,1021869,1030475,1040859,1052482,1060665,1068778,1084225,1104271,1113842,both
27,Nebraska,2253,3355,1939,2941,1088,1843,1826341,1840672,1853303,...,1879321,1891277,1905616,1915947,1925614,1934408,1961504,1963692,1975137,both
28,Nevada,3527,5227,5645,7143,2465,3981,2700551,2712730,2743996,...,2817628,2866939,2917563,2969905,3027341,3080156,3104614,3143991,3180944,both
29,New Hampshire,828,1472,1204,1719,732,1222,1316470,1320202,1324232,...,1333341,1336350,1342307,1348787,1353465,1359711,1377529,1388992,1395035,both
30,New Jersey,18164,22754,9605,13112,5969,8802,8791894,8828117,8844942,...,8864525,8867949,8870827,8885525,8886025,8882190,9288994,9267130,9306733,both
31,New Mexico,2886,4029,3704,4696,1722,2589,2059179,2080450,2087309,...,2089568,2089291,2091630,2091784,2092741,2096829,2117522,2115877,2120601,both
32,New York,16195,24159,14799,21623,8153,14113,19378102,19499241,19572932,...,19651049,19654666,19633428,19589572,19530351,19453561,20201249,19835913,19874063,both
33,North Carolina,8789,14645,15234,20521,7651,12227,9535483,9657592,9749476,...,9932887,10031646,10154788,10268233,10381615,10488084,10439388,10551162,10635801,both
34,North Dakota,1513,2061,939,1457,491,877,672591,685225,701176,...,737401,754066,754434,754942,758080,762062,779094,774948,783477,both
35,Ohio,15097,21502,20536,26208,10790,15362,11536504,11544663,11548923,...,11602700,11617527,11634370,11659650,11676341,11689100,11799448,11780017,11800309,both
36,Oklahoma,5248,8502,7850,10641,4156,6390,3751351,3788379,3818814,...,3878187,3909500,3926331,3931316,3940235,3956971,3959353,3986639,4006246,both
37,Oregon,1612,3251,4189,5539,2474,3717,3831074,3872036,3899001,...,3963244,4015792,4089976,4143625,4181886,4217737,4237256,4246155,4280745,both
38,Pennsylvania,18407,25388,20546,26482,10602,15677,12702379,12745815,12767118,...,12788313,12784826,12782275,12787641,12800922,12801989,13002700,12964056,12985862,both
39,Rhode Island,1918,2448,1217,1649,697,1013,1052567,1053649,1054621,...,1055936,1056065,1056770,1055673,1058287,1059361,1097379,1095610,1099196,both
40,South Carolina,5705,8775,9497,12121,4213,6495,4625364,4671994,4717354,...,4823617,4891938,4957968,5021268,5084156,5148714,5118425,5190705,5237816,both
41,South Dakota,1715,2278,987,1516,571,1012,814180,823579,833566,...,849129,853988,862996,872868,878698,884659,886667,895376,902142,both
42,Tennessee,7927,13381,13653,18369,6676,10572,6346105,6399291,6453898,...,6541223,6591170,6646010,6708799,6771631,6829174,6910840,6975218,7027644,both
43,Texas,33542,47720,48786,61138,17345,27353,25145561,25645629,26084481,...,26964333,27470056,27914410,28295273,28628666,28995881,29145505,29527941,29893139,both
44,Utah,1657,2702,2671,3514,1179,1946,2763885,2814384,2853375,...,2936879,2981835,3041868,3101042,3153550,3205958,3271616,3337975,3385815,both
45,Vermont,145,428,308,568,338,583,625741,627049,626090,...,625214,625216,623657,624344,624358,623989,643077,645570,647222,both
46,Virginia,6156,9407,9668,12695,5556,8071,8001024,8101155,8185080,...,8310993,8361808,8410106,8463587,8501286,8535519,8631393,8642274,8695711,both
47,Washington,3703,6957,6165,8778,3717,6240,6724540,6826627,6897058,...,7054655,7163657,7294771,7423362,7523869,7614893,7705281,7738692,7823204,both
48,West Virginia,1564,3180,3938,5542,2169,3851,1852994,1856301,1856872,...,1849489,1842050,1831023,1817004,1804291,1792147,1793716,1782959,1777122,both
49,Wisconsin,6286,8911,6076,8287,3457,5349,5686986,5705288,5719960,...,5751525,5760940,5772628,5790186,5807406,5822434,5893718,5895908,5913318,both
50,Wyoming,461,748,963,1191,318,512,563626,567299,576305,...,582531,585613,584215,578931,577601,578759,576851,578803,580067,both

In [16]:
# Commit merge
covid_rate=pop.merge(covid, on=['State'], indicator=True)

In [17]:
covid_rate.head()

,State,2010 Population,2011 Population,2012 Population,2013 Population,2014 Population,2015 Population,2016 Population,2017 Population,2018 Population,...,2020 Population,2021 Population,2022 Population,2020 COVID-19 Deaths,2020 COVID-Like Deaths,2021 COVID-19 Deaths,2021 COVID-Like Deaths,2022 COVID-19 Deaths,2022 COVID-Like Deaths,_merge
0,Alabama,4779736,4799069,4815588,4830081,4841799,4852347,4863525,4874486,4887681,...,5024279,5039877,5061555,6706,9870,9719,12496,3947,6134,both
1,Alaska,710231,722128,730443,737068,736283,737498,741456,739700,735139,...,733391,732673,734543,254,434,839,1005,311,478,both
2,Arizona,6392017,6472643,6554978,6632764,6730413,6829676,6941072,7044008,7158024,...,7151502,7276316,7350007,9321,13237,14060,17518,5172,7994,both
3,Arkansas,2915918,2940667,2952164,2959400,2967392,2978048,2989918,3001345,3009733,...,3011524,3025891,3035055,4027,6215,5336,7264,2558,4188,both
4,California,37253956,37638369,37948800,38260787,38596972,38918045,39167117,39358497,39461588,...,39538223,39237836,39403159,33578,52630,48327,64106,19836,33271,both

In [18]:
covid_rate.describe()

,2010 Population,2011 Population,2012 Population,2013 Population,2014 Population,2015 Population,2016 Population,2017 Population,2018 Population,2019 Population,2020 Population,2021 Population,2022 Population,2020 COVID-19 Deaths,2020 COVID-Like Deaths,2021 COVID-19 Deaths,2021 COVID-Like Deaths,2022 COVID-19 Deaths,2022 COVID-Like Deaths
count,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,5.100000e+01,51.000000,51.000000,51.000000,51.000000,51.000000,51.000000
mean,6.053834e+06,6.108958e+06,6.153549e+06,6.195955e+06,6.241196e+06,6.286964e+06,6.332183e+06,6.372265e+06,6.405637e+06,6.436069e+06,6.499006e+06,6.507720e+06,6.545544e+06,7125.156863,10553.274510,8904.647059,11837.450980,4279.058824,6792.901961
std,6.823984e+06,6.901810e+06,6.967073e+06,7.029241e+06,7.100271e+06,7.172361e+06,7.235904e+06,7.288670e+06,7.327258e+06,7.360660e+06,7.408023e+06,7.397955e+06,7.447394e+06,7578.975573,11160.936414,10659.253307,13783.601074,4324.949435,6970.532988
min,5.636260e+05,5.672990e+05,5.763050e+05,5.821220e+05,5.825310e+05,5.856130e+05,5.842150e+05,5.789310e+05,5.776010e+05,5.787590e+05,5.768510e+05,5.788030e+05,5.800670e+05,145.000000,428.000000,308.000000,568.000000,311.000000,478.000000
25%,1.696962e+06,1.712291e+06,1.724314e+06,1.732560e+06,1.740300e+06,1.746554e+06,1.756702e+06,1.767360e+06,1.777414e+06,1.789606e+06,1.816411e+06,1.841941e+06,1.852912e+06,1634.500000,2575.000000,2305.000000,3139.000000,1043.000000,1803.500000
50%,4.339367e+06,4.369821e+06,4.386346e+06,4.404659e+06,4.414349e+06,4.425976e+06,4.438182e+06,4.452268e+06,4.461153e+06,4.467673e+06,4.505836e+06,4.509394e+06,4.523562e+06,5162.000000,7977.000000,5907.000000,8118.000000,2998.000000,4920.000000
75%,6.636084e+06,6.720105e+06,6.780032e+06,6.838650e+06,6.908626e+06,6.996666e+06,7.117922e+06,7.233685e+06,7.340946e+06,7.446805e+06,7.428392e+06,7.507504e+06,7.586606e+06,9055.000000,13804.000000,9886.500000,13342.000000,5507.000000,8316.500000
max,3.725396e+07,3.763837e+07,3.794880e+07,3.826079e+07,3.859697e+07,3.891804e+07,3.916712e+07,3.935850e+07,3.946159e+07,3.951222e+07,3.953822e+07,3.923784e+07,3.940316e+07,33578.000000,52630.000000,48786.000000,64106.000000,19836.000000,33271.000000

In [19]:
covid_rate.columns

Index(['State', '2010 Population', '2011 Population', '2012 Population ',
       '2013 Population', '2014 Population', '2015 Population',
       '2016 Population', '2017 Population', '2018 Population',
       '2019 Population', '2020 Population', '2021 Population',
       '2022 Population', '2020 COVID-19 Deaths', '2020 COVID-Like Deaths',
       '2021 COVID-19 Deaths', '2021 COVID-Like Deaths',
       '2022 COVID-19 Deaths', '2022 COVID-Like Deaths', '_merge'],
      dtype='object')

In [21]:
covid_rate.shape

(51, 21)

In [23]:
covid_rate['_merge'].value_counts()

both          51
left_only      0
right_only     0
Name: _merge, dtype: int64

## Merge Successful

In [25]:
# Export data where the COVID-19 death rate will be calculated by state, for each year of the COVID-19 pandemic.
covid_rate.to_csv(r"C:\Users\miche\DA_Obesity and COVID19\02 Data\Prepared Data\03.03 COVID_CENSUS.csv")